import { Problem } from "../model";

export const problem: Problem<string, string> = {
    name: 'Break a Palindrome',
    id: 1328,
    url: 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/',
    solution: breakPalindrome,
    tests: [
        {
            id: 1,
            argument: "abccba",
            result: "aaccba"
        },
        {
            id: 2,
            argument: "a",
            result: ""
        },
        {
            id: 3,
            argument: "aba",
            result: "abb"
        }
    ]
}

function breakPalindrome(palindrome: string): string {
    // (almost) completely generated by copilot
    if (palindrome.length === 1) {
        return "";
    }
    const chars = palindrome.split("");
    for (let index = 0; index < Math.floor(chars.length / 2); index++) {
        if (chars[index] !== "a") {
            chars[index] = "a";
            return chars.join("");
        }
    }
    chars[chars.length - 1] = "b";
    return chars.join("");
};
